import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import NeedsAuth from "../components/NeedsAuth";
import { useStore, AUTH } from "../store/store";

const Home: NextPage = () => {
  const authed = useStore((state) => state.user.authed);
  const router = useRouter();

  React.useEffect(() => {
    if (authed === AUTH.AUTHED) {
      router.push("/users/fruit/create");
    }
  }, [authed]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NeedsAuth />
    </>
  );
};

export default Home;
